# Generated by Django 4.2.7 on 2023-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_user_item_inventory_alter_category_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
