# Generated by Django 4.2.7 on 2023-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_remove_item_inventory_remove_order_item_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
