# Generated by Django 4.2.7 on 2023-11-26 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_order_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 2, 11, 39, 336498)),
        ),
        migrations.AddField(
            model_name='user',
            name='table_no',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
