# Generated by Django 4.2.7 on 2023-11-26 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_user_expiry_user_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 2, 21, 3, 41516)),
        ),
    ]
