# Generated by Django 4.2.7 on 2023-11-26 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_user_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 15, 7, 11, 665516, tzinfo=datetime.timezone.utc)),
        ),
    ]
