# Generated by Django 4.2.7 on 2023-11-27 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0016_alter_user_expiry_alter_user_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tableorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_no_order', to='resto.order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiry',
            field=models.TimeField(default=datetime.time(12, 58, 36, 119671)),
        ),
    ]
