# Generated by Django 4.2.7 on 2023-11-27 04:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0017_user_tableorder_alter_user_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tableorder',
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiry',
            field=models.TimeField(default=datetime.time(13, 13, 43, 127998)),
        ),
    ]
