# Generated by Django 4.2.7 on 2023-11-27 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0018_remove_user_tableorder_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry',
            field=models.TimeField(default=datetime.time(13, 14, 33, 480923)),
        ),
    ]
