# Generated by Django 4.2.7 on 2023-11-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_closed_alter_comment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
